ONNX版Raspberry Pi向け自動ビルド（armhf）の追加 (#41)
* add onnxruntime-armhf build

* cache artifact

* cache key

* cache build result

* reduce skips to use image contents

* use image digest as cache key

* cache key

* core build

* armhf artifact

* keep libonnxruntime for armhf

* suffix

* fix env

* quote

* fix env

* fix env

* versioned shared object only

* copy cpp-shared artifacts only for release

* cache build artifact as docker image

* build on ci environment directly to reuse build script

* onnx runtime version as env

* fix syntax

* sudo

* cache key

* cache key

* fix cc/cxx env

* cc/cxx for cmake

* revert cc/cxx for cmake

* add qemu

* add comment

* remove -E

* copy docs to packed onnxruntime dir

* rsync

* checkout to create onnx runtime artifact

* load cache after checkout

* fix removal

* mv verbose

* use artifact dir

* fix libonnxruntime copy

* copy libcore to artifact dirs

* remove duplicated files

* fix path

* add comment

* update comment

* ignore copy error

* use onnxruntime repo commit id for GIT_COMMIT_ID

* build only on main branch due to long build time

* add use_openmp

* use ONNX Runtime v1.9.0

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* Update build.yml

* prepend CMAKE_SYSTEM_PROCESSOR

* move apply patch step

* cmake_extra_defines

* comment out prepend CMAKE_SYSTEM_PROCESSOR

* add CMAKE_SYSTEM_NAME=Generic

* SYSTEM_NAME Linux

* remove additional patch pr9029

* remove prepend code

* revert branch limit

* rm unused cmake_system_processor

* exec build-cpp-shared even if build-onnxruntime failed

* fix comment

* fix comment

* fix comment

* add ignore

* add comment to configure build environment

* add comment

* update doc

* fix heading

* add onnx runtime link

* remove DOCKER_ env

* add ARCH_PREFIX, ARCH_SUFFIX usage comment

* add comment: copy shared lib if exists

* use artifact_name dir for packed onnxruntime

* pack onnxruntime for all env

* fix dylib copy

* copy with find and xargs

* fix xargs usage

* revert copy all onnxruntime

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,7 +15,148 @@ env:
   SKIP_UPLOADING_RELEASE_ASSET: ${{ secrets.SKIP_UPLOADING_RELEASE_ASSET || '1' }}
 
 jobs:
+  build-onnxruntime:
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - artifact_name: onnxruntime-linux-armhf-cpu
+            os: ubuntu-18.04
+            cc_version: '8'
+            cxx_version: '8'
+            arch: arm-linux-gnueabihf
+            ld_symlink_name: ld-linux-armhf.so.3
+            build_opts: --arm --cmake_extra_defines CMAKE_SYSTEM_NAME=Linux CMAKE_SYSTEM_PROCESSOR=armv7l --use_openmp --config Release --parallel --update --build --build_shared_lib
+            result_dir: build/Linux/Release
+
+    env:
+      ONNXRUNTIME_VERSION: v1.9.1
+      # prefix usage: "", "arm-linux-gnueabihf-" => "gcc-8", "arm-linux-gnueabihf-gcc-8" (command name)
+      # suffix usage: "", "-arm-linux-gnueabihf" => "gcc-8", "gcc-8-arm-linux-gnueabihf" (package name)
+      ARCH_PREFIX: "${{ (matrix.arch != '' && matrix.arch) || '' }}${{ (matrix.arch != '' && '-') || '' }}"
+      ARCH_SUFFIX: "${{ (matrix.arch != '' && '-') || '' }}${{ (matrix.arch != '' && matrix.arch) || '' }}"
+
+    runs-on: ${{ matrix.os }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          repository: microsoft/onnxruntime
+          submodules: true
+          ref: ${{ env.ONNXRUNTIME_VERSION }}
+
+      - name: Dump matrix context
+        env:
+          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
+        run: echo "$MATRIX_CONTEXT" > matrix.json
+
+      - name: Cache build result
+        id: cache-build-result
+        uses: actions/cache@v2
+        with:
+          path: build/
+          key: ${{ matrix.artifact_name }}-${{ env.ONNXRUNTIME_VERSION }}-cache-v1-${{ hashFiles('matrix.json') }}
+
+      - name: Install build dependencies
+        if: steps.cache-build-result.outputs.cache-hit != 'true'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y \
+              build-essential \
+              git \
+              wget \
+              qemu-user-binfmt \
+              gcc-${{ matrix.cc_version }}${{ env.ARCH_SUFFIX }} \
+              g++-${{ matrix.cxx_version }}${{ env.ARCH_SUFFIX }} \
+              python3
+
+      # ONNX Runtime v1.9.0 requires CMake 3.18 or higher.
+      - name: Install CMake
+        if: steps.cache-build-result.outputs.cache-hit != 'true'
+        env:
+          CMAKE_VERSION: 3.22.0-rc2
+        run: |
+          wget -O cmake.sh "https://github.com/Kitware/CMake/releases/download/v${{ env.CMAKE_VERSION }}/cmake-${{ env.CMAKE_VERSION }}-linux-x86_64.sh"
+          sudo bash cmake.sh --skip-license --prefix=/usr/local
+
+      - name: Configure build environment
+        if: steps.cache-build-result.outputs.cache-hit != 'true'
+        run: |
+          # Required for arm build
+          # https://github.com/microsoft/onnxruntime/issues/4189#issuecomment-642528278
+          echo 'string(APPEND CMAKE_C_FLAGS " -latomic")' >> cmake/CMakeLists.txt
+          echo 'string(APPEND CMAKE_CXX_FLAGS " -latomic")' >> cmake/CMakeLists.txt
+
+          # Prevent Exec Format Error during cross-compiling
+          if [ -n "${{ matrix.ld_symlink_name }}" ]; then
+            sudo ln -s /usr/${{ matrix.arch }}/lib /lib/${{ matrix.arch }}
+            sudo ln -s /lib/${{ matrix.arch }}/ld-*.so /lib/${{ matrix.ld_symlink_name }}
+          fi
+
+      - name: Build ONNX Runtime
+        if: steps.cache-build-result.outputs.cache-hit != 'true'
+        env:
+          CC: ${{ env.ARCH_PREFIX }}gcc-${{ matrix.cc_version }}
+          CXX: ${{ env.ARCH_PREFIX }}g++-${{ matrix.cxx_version }}
+        run: |
+          # add --arm for gcc-8: https://github.com/microsoft/onnxruntime/issues/4189
+          # skip test: https://github.com/microsoft/onnxruntime/issues/2436
+          # ONNX Runtime v1.9.0 requires CMAKE_SYSTEM_PROCESSOR, https://github.com/microsoft/onnxruntime/releases/tag/v1.9.0
+          # Both CMAKE_SYSTEM_NAME and CMAKE_SYSTEM_PROCESSOR are required.
+          bash ./build.sh ${{ matrix.build_opts }}
+
+      - name: Organize artifact
+        run: |
+          mkdir artifact
+
+          # copy shared lib
+          mkdir artifact/lib
+
+          NAME=$(basename ${{ matrix.result_dir }}/libonnxruntime.so.*)
+          cp "${{ matrix.result_dir }}/${NAME}" artifact/lib/
+          ln -s "${NAME}" artifact/lib/libonnxruntime.so
+
+          # copy header files
+          mkdir artifact/include
+
+          readarray -t HEADERS <<EOF
+          onnxruntime/core/session/onnxruntime_c_api.h
+          onnxruntime/core/session/onnxruntime_cxx_api.h
+          onnxruntime/core/session/onnxruntime_cxx_inline.h
+          onnxruntime/core/providers/cpu/cpu_provider_factory.h
+          onnxruntime/core/session/onnxruntime_session_options_config_keys.h
+          onnxruntime/core/session/onnxruntime_run_options_config_keys.h
+          onnxruntime/core/framework/provider_options.h
+          EOF
+
+          for path in "${HEADERS[@]}"; do
+            cp "include/${path}" ./artifact/include/
+          done
+
+          # copy docs & license
+          cp VERSION_NUMBER ./artifact/
+          cp LICENSE ./artifact/
+          cp ThirdPartyNotices.txt ./artifact/
+          cp docs/Privacy.md ./artifact/
+          cp README.md ./artifact/
+
+          echo "$(git rev-parse HEAD)" >> ./artifact/GIT_COMMIT_ID
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: ${{ matrix.artifact_name }}
+          path: artifact/*
+          retention-days: 7
+
+
   build-cpp-shared:
+    # Execute this job even if build-onnxruntime failed
+    if: always()
+    needs:
+      - build-onnxruntime
+
     strategy:
       fail-fast: false
       matrix:
@@ -59,13 +200,31 @@ jobs:
             onnxruntime_url: https://github.com/microsoft/onnxruntime/releases/download/v1.9.0/onnxruntime-linux-x64-gpu-1.9.0.tgz
             cmake_additional_options: -DENABLE_CUDA=ON
             artifact_name: linux-x64-gpu
+            cc_version: '8'
+            cxx_version: '8'
 
           - os: ubuntu-18.04
             device: cpu-x64
             onnxruntime_url: https://github.com/microsoft/onnxruntime/releases/download/v1.9.0/onnxruntime-linux-x64-1.9.0.tgz
             artifact_name: linux-x64-cpu
+            cc_version: '8'
+            cxx_version: '8'
+
+          - os: ubuntu-18.04
+            device: cpu-armhf
+            onnxruntime_artifact_name: onnxruntime-linux-armhf-cpu
+            artifact_name: linux-armhf-cpu
+            cc_version: '8'
+            cxx_version: '8'
+            arch: arm-linux-gnueabihf
 
     runs-on: ${{ matrix.os }}
+
+    env:
+      # prefix usage: "", "arm-linux-gnueabihf-" => "gcc-8", "arm-linux-gnueabihf-gcc-8" (command name)
+      # suffix usage: "", "-arm-linux-gnueabihf" => "gcc-8", "gcc-8-arm-linux-gnueabihf" (package name)
+      ARCH_PREFIX: "${{ (matrix.arch != '' && matrix.arch) || '' }}${{ (matrix.arch != '' && '-') || '' }}"
+      ARCH_SUFFIX: "${{ (matrix.arch != '' && '-') || '' }}${{ (matrix.arch != '' && matrix.arch) || '' }}"
 
     steps:
       - uses: actions/checkout@v2
@@ -74,19 +233,21 @@ jobs:
 
       # ONNX Runtime
       - name: Export ONNX Runtime url to calc hash
+        if: matrix.onnxruntime_artifact_name == ''
         shell: bash
         run: echo "${{ matrix.onnxruntime_url }}" > download/onnxruntime_url.txt
 
       - name: Cache ONNX Runtime
+        if: matrix.onnxruntime_artifact_name == ''
         uses: actions/cache@v2
         id: onnxruntime-cache
         with:
-          key: ${{ matrix.os }}-${{ matrix.device }}-onnxruntime-cache-v1-${{ hashFiles('download/onnxruntime_url.txt') }}
+          key: onnxruntime-cache-v1-${{ hashFiles('download/onnxruntime_url.txt') }}
           path: download/onnxruntime
 
       # download/onnxruntime/lib/onnxruntime.dll
       - name: Download ONNX Runtime (zip)
-        if: steps.onnxruntime-cache.outputs.cache-hit != 'true' && endsWith(matrix.onnxruntime_url, '.zip')
+        if: matrix.onnxruntime_artifact_name == '' && steps.onnxruntime-cache.outputs.cache-hit != 'true' && endsWith(matrix.onnxruntime_url, '.zip')
         shell: bash
         run: |
           curl -L "${{ matrix.onnxruntime_url }}" > download/onnxruntime.zip
@@ -103,13 +264,20 @@ jobs:
       # download/onnxruntime/lib/libonnxruntime.so
       # download/onnxruntime/lib/libonnxruntime.dylib
       - name: Download ONNX Runtime (tgz)
-        if: steps.onnxruntime-cache.outputs.cache-hit != 'true' && endsWith(matrix.onnxruntime_url, '.tgz')
+        if: matrix.onnxruntime_artifact_name == '' && steps.onnxruntime-cache.outputs.cache-hit != 'true' && endsWith(matrix.onnxruntime_url, '.tgz')
         shell: bash
         run: |
           curl -L "${{ matrix.onnxruntime_url }}" > download/onnxruntime.tgz
           mkdir -p download/onnxruntime
           tar xf download/onnxruntime.tgz -C download/onnxruntime --strip-components 1
           rm download/onnxruntime.tgz
+
+      - name: Download ONNX Runtime (artifact)
+        if: matrix.onnxruntime_artifact_name != ''
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ matrix.onnxruntime_artifact_name }}
+          path: download/onnxruntime/
 
       # Build
       - if: startsWith(matrix.os, 'windows')
@@ -119,12 +287,15 @@ jobs:
         uses: jwlawson/actions-setup-cmake@v1.9
 
       # gcc 7 (ubuntu-18.04 default) does not have stdc++fs
-      - name: Install build-essential
+      - name: Install build dependencies
         if: startsWith(matrix.os, 'ubuntu')
         shell: bash
         run: |
           sudo apt-get update
-          sudo apt-get install -y gcc-8 g++-8 cmake
+          sudo apt-get install -y \
+            gcc-${{ matrix.cc_version }}${{ env.ARCH_SUFFIX }} \
+            g++-${{ matrix.cxx_version }}${{ env.ARCH_SUFFIX }} \
+            cmake
 
       - name: Configure (Windows, macOS)
         if: ${{ !startsWith(matrix.os, 'ubuntu') }} # '!' cannot be used as a first character in YAML
@@ -138,8 +309,8 @@ jobs:
         shell: bash
         working-directory: onnx
         env:
-          CC:   gcc-8
-          CXX:  g++-8
+          CC: ${{ env.ARCH_PREFIX }}gcc-${{ matrix.cc_version }}
+          CXX: ${{ env.ARCH_PREFIX }}g++-${{ matrix.cxx_version }}
         run: |
           cmake -DONNXRUNTIME_DIR=../download/onnxruntime ${{ matrix.cmake_additional_options }} .
 
@@ -152,16 +323,40 @@ jobs:
           # copy lib to onnx/lib/* and set rpath (linux)
           cmake --install .
 
+      - name: Organize artifact
+        shell: bash
+        run: |
+          mkdir artifact
+
           # remove files with duplicate names to create a flat release archive
-          cd lib
-          rm -f onnxruntime* libonnxruntime* core.h core.lib
+          rm -vf onnx/lib/core.h onnx/lib/core.lib
+
+          # copy Windows DLL if exists
+          cp -v onnx/lib/core* artifact/ || true
+          # copy Linux/macOS shared library if exists
+          cp -v onnx/lib/libcore* artifact/ || true
+
+          # copy libonnxruntime
+          if [ "${{ matrix.onnxruntime_artifact_name }}" != "" ]; then
+            mkdir -p "artifact/onnxruntime-${{ matrix.artifact_name }}/"
+
+            # copy docs and license (all files in root dir)
+            find "download/onnxruntime/" -maxdepth 1 -type f | xargs -I{} cp -v {} "artifact/onnxruntime-${{ matrix.artifact_name }}/"
+
+            # copy Windows DLL if exists
+            cp -v onnx/lib/onnxruntime* "artifact/onnxruntime-${{ matrix.artifact_name }}/" || true
+            # copy Linux shared library if exists
+            cp -v onnx/lib/libonnxruntime.so.* "artifact/onnxruntime-${{ matrix.artifact_name }}/" || true
+            # copy macOS shared library if exists
+            cp -v onnx/lib/libonnxruntime.dylib "artifact/onnxruntime-${{ matrix.artifact_name }}/" || true
+          fi
 
       # Upload
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with:
           name: ${{ matrix.artifact_name }}-cpp-shared
-          path: onnx/lib/*
+          path: artifact/*
           retention-days: 7
 
   # Create core.zip
@@ -200,6 +395,7 @@ jobs:
           osx-x64-cpu       libcore.dylib libcore_cpu_x64.dylib
           linux-x64-gpu     libcore.so    libcore_gpu_x64_nvidia.so
           linux-x64-cpu     libcore.so    libcore_cpu_x64.so
+          linux-armhf-cpu   libcore.so    libcore_cpu_armhf.so
           EOF
 
           for line in "${MAPPINGS[@]}"; do
@@ -213,10 +409,10 @@ jobs:
             fi
 
             echo "Renaming ${KND}/${SRC} => ${DST}"
-            mv "artifacts/${KND}-cpp-shared/${SRC}" "artifacts/${KND}-cpp-shared/${DST}"
+            mv -v "artifacts/${KND}-cpp-shared/${SRC}" "artifacts/${KND}-cpp-shared/${DST}"
           done
 
-          mv artifacts/*/* release/
+          mv -v artifacts/*-cpp-shared/* release/
 
           cp core.h release/
 
