エラーメッセージ

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -166,7 +166,10 @@ jobs:
               -H 'X-GitHub-Api-Version: 2022-11-28' \
               -q '[.] | flatten | any(.ref == "refs/tags/'"$VERSION"'")'
           )
-          [ "$exists" = false ]
+          if [ "$exists" = true ]; then
+            echo "::error title=Duplicated tag::'refs/tags/$VERSION' already exists"
+            exit 1
+          fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -178,7 +181,10 @@ jobs:
               --json tagName \
               -q 'any(.tagName == "'"$VERSION"'")'
           )
-          [ "$found_recent" = false ]
+          if [ "$found_recent" = true ]; then
+            echo "::error title=Duplicated release::Found a draft that has the same 'tagName'"
+            exit 1
+          fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
