build: リリース後の`download_test`ではリリースのdownloaderを使う

diff --git a/.github/workflows/download_test.yml b/.github/workflows/download_test.yml
--- a/.github/workflows/download_test.yml
+++ b/.github/workflows/download_test.yml
@@ -21,6 +21,7 @@ on:
 
 env:
   VERSION: ${{ inputs.version || 'prerelease-latest' }}
+  USE_RELEASED_DOWNLOADER: ${{ github.event_name == 'workflow_call' }}
 
 defaults:
   run:
@@ -36,7 +37,7 @@ jobs:
         include:
           - name: 通常ダウンロード
             os: windows-latest
-            download_command: cargo run -v -p downloader -- # バージョン指定のために -- が必要
+            additional_args: # バージョン指定のために -- が必要
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -49,7 +50,7 @@ jobs:
               additional_libraries/
           - name: CpuArch指定
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --cpu-arch x86
+            additional_args: --cpu-arch x86
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -60,7 +61,7 @@ jobs:
               additional_libraries/
           - name: output先指定ダウンロード
             os: windows-latest
-            download_command: cargo run -v -p downloader -- -o other_output
+            additional_args: -o other_output
             download_dir: other_output
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -71,7 +72,7 @@ jobs:
               additional_libraries/
           - name: Min option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --min
+            additional_args: --min
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -83,7 +84,7 @@ jobs:
               dict/
           - name: DirectML option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices directml
+            additional_args: --devices directml
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -101,7 +102,7 @@ jobs:
               additional_libraries/*curand*
           - name: DirectMLかつMin option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices directml --min
+            additional_args: --devices directml --min
             download_dir: voicevox_core
             check_items: |
               c_api/README.txt
@@ -113,7 +114,7 @@ jobs:
               dict/
           - name: cuda option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices cuda
+            additional_args: --devices cuda
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -135,7 +136,7 @@ jobs:
               additional_libraries/*directml*
           - name: cudaかつmin option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices cuda --min
+            additional_args: --devices cuda --min
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -166,7 +167,26 @@ jobs:
         # TODO: voicevox_vvm 0.16.0のprerelease指定を外したら`--models-version`の指定をやめる
         # `"y"`を流し込むことで「利用規約への同意」を行う
         # (この際`echo y`ではなく`yes`を使うと謎の要因により無言で異常終了する)
-        run: echo y | ${{ matrix.download_command }} --c-api-version ${{ env.VERSION }} --c-api-repo ${{ github.repository }} --onnxruntime-version voicevox_onnxruntime-1.17.3 --models-version 0.16.0
+        run: |
+          common_opts='--c-api-version ${{ env.VERSION }} --c-api-repo ${{ github.repository }} --onnxruntime-version voicevox_onnxruntime-1.17.3 --models-version 0.16.0'
+
+          # shellcheck disable=SC2086
+          echo y | if [ "$USE_RELEASED_DOWNLOADER" = true ]; then
+            case "$RUNNER_OS,$RUNNER_ARCH" in
+              Windows,X64) downloader_name=download-windows-x64.exe ;;
+              Linux,X64) downloader_name=x86_64-unknown-linux-gnu ;;
+              Linux,ARM64) downloader_name=aarch64-unknown-linux-gnu ;;
+              macOS,X64) downloader_name=x86_64-apple-darwin ;;
+              macOS,ARM64) downloader_name=aarch64-apple-darwin ;;
+              *)
+                echo "::error title=Execute download command::No downloader for ($RUNNER_OS, $RUNNER_ARCH)"
+                exit 1
+            esac
+            gh release download "$VERSION" -p $downloader_name
+            ./$downloader_name $common_opts ${{ matrix.additional_args }}
+          else
+            cargo run -v -p downloader -- $common_opts ${{ matrix.additional_args }}
+          fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Check downloaded version
