build: リリース後の`download_test`ではリリースのdownloaderを使う (#1303)
リリース後のテストとして強度を高めるためと、あとは時間短縮のため。

diff --git a/.github/workflows/download_test.yml b/.github/workflows/download_test.yml
--- a/.github/workflows/download_test.yml
+++ b/.github/workflows/download_test.yml
@@ -30,6 +30,7 @@ jobs:
     runs-on: ubuntu-slim
     outputs:
       version: ${{ inputs.version || 'prerelease-latest' }}
+      use-released-downloader: ${{ !!inputs.version }}
     steps:
       - name: NOP
         run: ':'
@@ -42,7 +43,7 @@ jobs:
         include:
           - name: 通常ダウンロード
             os: windows-latest
-            download_command: cargo run -v -p downloader -- # バージョン指定のために -- が必要
+            additional_opts: ''
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -55,7 +56,7 @@ jobs:
               additional_libraries/
           - name: CpuArch指定
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --cpu-arch x86
+            additional_opts: --cpu-arch x86
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -66,7 +67,7 @@ jobs:
               additional_libraries/
           - name: output先指定ダウンロード
             os: windows-latest
-            download_command: cargo run -v -p downloader -- -o other_output
+            additional_opts: -o other_output
             download_dir: other_output
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -77,7 +78,7 @@ jobs:
               additional_libraries/
           - name: Min option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --min
+            additional_opts: --min
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -89,7 +90,7 @@ jobs:
               dict/
           - name: DirectML option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices directml
+            additional_opts: --devices directml
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -107,7 +108,7 @@ jobs:
               additional_libraries/*curand*
           - name: DirectMLかつMin option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices directml --min
+            additional_opts: --devices directml --min
             download_dir: voicevox_core
             check_items: |
               c_api/README.txt
@@ -119,7 +120,7 @@ jobs:
               dict/
           - name: cuda option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices cuda
+            additional_opts: --devices cuda
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -141,7 +142,7 @@ jobs:
               additional_libraries/*directml*
           - name: cudaかつmin option確認
             os: windows-latest
-            download_command: cargo run -v -p downloader -- --devices cuda --min
+            additional_opts: --devices cuda --min
             download_dir: voicevox_core
             check_items: |
               c_api/lib/voicevox_core.dll
@@ -155,7 +156,9 @@ jobs:
     name: ${{ matrix.name }}-${{ matrix.os }}
     steps:
       - uses: actions/checkout@v5
+        if: '!fromJson(needs.config.outputs.use-released-downloader)'
       - name: Set up Rust
+        if: '!fromJson(needs.config.outputs.use-released-downloader)'
         uses: ./.github/actions/rust-toolchain-from-file
       - name: Determine version
         run: |
@@ -174,7 +177,34 @@ jobs:
         # TODO: voicevox_vvm 0.16.0のprerelease指定を外したら`--models-version`の指定をやめる
         # `"y"`を流し込むことで「利用規約への同意」を行う
         # (この際`echo y`ではなく`yes`を使うと謎の要因により無言で異常終了する)
-        run: echo y | ${{ matrix.download_command }} --c-api-version ${{ env.VERSION }} --c-api-repo ${{ github.repository }} --onnxruntime-version voicevox_onnxruntime-1.17.3 --models-version 0.16.0
+        run: |
+          use_released_downloader=${{ needs.config.outputs.use-released-downloader }}
+
+          opts=(
+            --c-api-version "$VERSION"
+            --c-api-repo "$GITHUB_REPOSITORY"
+            --onnxruntime-version voicevox_onnxruntime-1.17.3
+            --models-version 0.16.0
+          )
+          opts+=(${{ matrix.additional_opts }})
+
+          echo y | if [ $use_released_downloader = true ]; then
+            case "$RUNNER_OS,$RUNNER_ARCH" in
+              Windows,X64) downloader_name=download-windows-x64.exe ;;
+              Linux,X64) downloader_name=download-linux-x64 ;;
+              Linux,ARM64) downloader_name=download-linux-arm64 ;;
+              macOS,X64) downloader_name=download-osx-x64 ;;
+              macOS,ARM64) downloader_name=download-osx-arm64 ;;
+              *)
+                echo "::error title=Execute download command::Unexpected runner: ($RUNNER_OS, $RUNNER_ARCH)"
+                exit 1
+            esac
+            gh release -R "$GITHUB_REPOSITORY" download "$VERSION" -p $downloader_name
+            chmod u+x ./$downloader_name
+            ./$downloader_name "${opts[@]}"
+          else
+            cargo run -v -p downloader -- "${opts[@]}"
+          fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Check downloaded version
