remove!: `requires-python`を`>=3.10`に引き上げる (#915)
`requires-python`を`>=3.10`に引き上げた上、 #873 の解決を確認する。

Python 3.9, 3.10の機能を使うことは別PRで行う。

Resolves: #873

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,10 +39,10 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y shellcheck
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v5
         with:
-          python-version: "3.8"
+          python-version: "3.10"
       - name: Install Pyflakes
         run: pip install 'pyflakes>3,<4'
       - name: actionlint
@@ -67,10 +67,10 @@ jobs:
         uses: ./.github/actions/rust-toolchain-from-file
         with:
           components: clippy,rustfmt
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v5
         with:
-          python-version: "3.8"
+          python-version: "3.10"
       - uses: Swatinem/rust-cache@v2
       - run: cargo clippy -v --tests -- -D clippy::all -D warnings --no-deps
       - run: cargo clippy -v -- -D clippy::all -D warnings --no-deps
@@ -125,10 +125,10 @@ jobs:
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v4
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v5
         with:
-          python-version: "3.8"
+          python-version: "3.10"
       - name: Set up Rust
         uses: ./.github/actions/rust-toolchain-from-file
       - uses: Swatinem/rust-cache@v2
@@ -272,10 +272,10 @@ jobs:
         working-directory: ./crates/voicevox_core_python_api
     steps:
       - uses: actions/checkout@v4
-      - name: Set up Python 3.8
+      - name: Set up Python 3.10
         uses: actions/setup-python@v5
         with:
-          python-version: "3.8"
+          python-version: "3.10"
       - name: Set up Rust
         uses: ./.github/actions/rust-toolchain-from-file
       - run: |
@@ -295,6 +295,18 @@ jobs:
         run: |
           for file in ../../example/python/run{,-asyncio}.py; do
             poetry run python "$file" ../test_util/data/model/sample.vvm --dict-dir ../test_util/data/open_jtalk_dic_utf_8-1.11
+          done
+          # https://github.com/VOICEVOX/voicevox_core/issues/873 が再発しないかの確認。
+          #
+          # Python 3.8においては、プロセスの終了までにFatal Python errorに至らなくても`StopIteration`までは達することが多い。
+          # #873の要因は依然として不明であるが、`StopIteration`が出ないことの確認をもって#873の解決とすることにする。
+          #
+          # TODO: 10回の実行におよそ60秒ほどかかるため、状況の経過を見てやめる。
+          for _ in {1..10}; do
+            poetry run python ../../example/python/run-asyncio.py ../test_util/data/model/sample.vvm --dict-dir ../test_util/data/open_jtalk_dic_utf_8-1.11 \
+              2> >(tee ./stderr.txt >&2)
+            # shellcheck disable=SC2059
+            ! grep -q StopIteration ./stderr.txt
           done
   build-and-test-java-api:
     strategy:
